# Site settings
title: Torypages
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Someone please give me a description. 
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  torypages
excerpt_separator: <!-- read more -->
paginate: 15

# Build settings
markdown: redcarpet
